import { Alert, Button, Card, Form, Input, InputNumber, Space, Table, Tag, Typography, message, Modal } from 'antd';
import { PlusOutlined, CheckOutlined, CloseOutlined } from '@ant-design/icons';
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { approveApplication, getApplications, rejectApplication } from '../services/applications';
import type { Application } from '../types/api';
import { ApiError } from '../lib/http';
import { useAuth } from '../lib/auth';
const statusMap: Record<string, { text: string; color: string }> = { pending: { text: '待审批', color: 'processing' }, approved: { text: '已通过', color: 'success' }, rejected: { text: '已驳回', color: 'error' }, cancelled: { text: '已取消', color: 'default' } };
const typeMap: Record<string, string> = { quota: '额度申请', extra_usage: '额外使用', budget_increase: '预算追加', tool_access: '工具权限' };
const stageMap: Record<string, { text: string; color: string }> = { manager: { text: '待主管审批', color: 'gold' }, budget_admin: { text: '待预算员审批', color: 'purple' }, completed: { text: '流程完成', color: 'green' } };
export function ApplicationsPage() {
  const { user } = useAuth(); const navigate = useNavigate(); const [rows, setRows] = useState<Application[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [reviewing, setReviewing] = useState<Application | null>(null); const [reviewAction, setReviewAction] = useState<'approve'|'reject'>('approve'); const [form] = Form.useForm(); const canReview = user?.role === 'manager' || user?.role === 'budget_admin';
  const load = () => { setLoading(true); getApplications({ page: 1, pageSize: 20 }).then(result => setRows(result.items)).catch(e => setError(e instanceof ApiError ? e.message : '申请列表加载失败')).finally(() => setLoading(false)); }; useEffect(load, []);
  const submitReview = async () => { try { const values = await form.validateFields(); const result = reviewAction === 'approve' ? await approveApplication(reviewing!.id, values.comment, values.approvedAmount) : await rejectApplication(reviewing!.id, values.comment); message.success(result.message ?? (reviewAction === 'approve' ? '审批操作成功' : '申请已驳回')); setReviewing(null); form.resetFields(); load(); } catch (e) { if (!(e as { errorFields?: unknown }).errorFields) message.error(e instanceof Error ? e.message : '提交失败，请稍后重试'); } };
  const canApproveRow = (row: Application) => row.status === 'pending' && canReview && ((user?.role === 'manager' && row.approvalStage === 'manager') || (user?.role === 'budget_admin' && row.approvalStage === 'budget_admin'));
  const columns = [{ title: '申请编号', dataIndex: 'applicationNo' }, { title: '申请类型', dataIndex: 'type', render: (value: string) => typeMap[value] ?? value }, { title: '申请人', dataIndex: 'applicantName' }, { title: '部门', dataIndex: 'departmentName' }, { title: '申请金额', dataIndex: 'requestedAmount', render: (value: number) => `¥ ${value.toLocaleString()}` }, { title: '审批阶段', dataIndex: 'approvalStage', render: (value: string) => <Tag color={stageMap[value]?.color}>{stageMap[value]?.text ?? value}</Tag> }, { title: '状态', dataIndex: 'status', render: (value: string) => <Tag color={statusMap[value]?.color}>{statusMap[value]?.text ?? value}</Tag> }, { title: '提交时间', dataIndex: 'submittedAt', render: (value?: string) => value ? new Date(value).toLocaleString('zh-CN') : '-' }, { title: '操作', render: (_: unknown, row: Application) => canApproveRow(row) ? <Space><Button size="small" type="link" icon={<CheckOutlined />} onClick={() => { setReviewAction('approve'); setReviewing(row); }}>通过</Button><Button size="small" danger type="link" icon={<CloseOutlined />} onClick={() => { setReviewAction('reject'); setReviewing(row); }}>驳回</Button></Space> : <Button type="link" size="small" onClick={() => navigate(`/applications/${row.id}`)}>详情</Button> }];
  return <div className="page-wrap"><div className="page-title"><div><Typography.Title level={2}>申请与审批</Typography.Title><Typography.Paragraph type="secondary">管理额度、额外使用和年度预算追加申请。</Typography.Paragraph></div><Button type="primary" icon={<PlusOutlined />} onClick={() => navigate('/applications/new')}>新建申请</Button></div>{error && <Alert type="error" showIcon message={error} action={<a onClick={load}>重新加载</a>} />}<Card><Table rowKey="id" loading={loading} dataSource={rows} columns={columns} scroll={{ x: 1000 }} pagination={{ pageSize: 20, showTotal: total => `共 ${total} 条` }} /></Card><Modal title={reviewAction === 'approve' ? '审批通过' : '驳回申请'} open={Boolean(reviewing)} onCancel={() => setReviewing(null)} onOk={submitReview} okText="确认" cancelText="取消"><Form form={form} layout="vertical"><Form.Item name="approvedAmount" label="通过金额" rules={reviewAction === 'approve' ? [{ required: true, type: 'number', min: 0.01, message: '请输入有效金额' }] : []} initialValue={reviewing?.requestedAmount}><InputNumber style={{ width: '100%' }} disabled={reviewAction === 'reject'} min={0.01} precision={2} /></Form.Item><Form.Item name="comment" label="审批意见" rules={[{ required: true, whitespace: true, message: '请输入审批意见' }]}><Input.TextArea rows={4} placeholder="请输入审批意见" /></Form.Item></Form></Modal></div>;
}
