import { Alert, Card, Col, Progress, Row, Space, Statistic, Table, Tag, Typography, message } from 'antd';
import { ArrowUpOutlined, BellOutlined, DollarOutlined, FundOutlined, WarningOutlined } from '@ant-design/icons';
import { useEffect, useState } from 'react';
import { getDashboardOverview } from '../services/auth';
import type { DashboardOverview } from '../types/api';
import { ApiError } from '../lib/http';

const trend = [{ month: '1月', amount: 120 }, { month: '2月', amount: 142 }, { month: '3月', amount: 136 }, { month: '4月', amount: 178 }, { month: '5月', amount: 165 }, { month: '6月', amount: 212 }, { month: '7月', amount: 205 }, { month: '8月', amount: 248 }];
const deptRows = [{ key: 1, dept: '产品研发部', rate: 58.3, amount: 486200 }, { key: 2, dept: '数据平台部', rate: 52.1, amount: 302680 }, { key: 3, dept: '市场品牌部', rate: 49.7, amount: 216450 }, { key: 4, dept: '客户成功部', rate: 42.4, amount: 168920 }];
const projectRows = [{ key: 1, project: 'CRM 重构项目', dept: '产品研发部', amount: 86420 }, { key: 2, project: '数据平台项目', dept: '数据平台部', amount: 72850 }, { key: 3, project: '品牌内容中台', dept: '市场品牌部', amount: 43280 }];
const money = (value: number) => `¥ ${value.toLocaleString('zh-CN', { maximumFractionDigits: 0 })}`;
export function DashboardPage() { const [data, setData] = useState<DashboardOverview | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { getDashboardOverview(2026).then(setData).catch(e => { setError(e instanceof ApiError ? e.message : '工作台数据加载失败'); message.error('工作台数据加载失败'); }).finally(() => setLoading(false)); }, []); const budget = data?.budget ?? { totalAmount: 0, usedAmount: 0, remainingAmount: 0, executionRate: 0 }; const quota = data?.quota ?? { allocatedAmount: 0, usedAmount: 0, remainingAmount: 0, usageRate: 0 };
  return <div className="page-wrap"><div className="page-title"><div><Typography.Text className="eyebrow">AI COST CONTROL CENTER</Typography.Text><Typography.Title level={2}>费用驾驶舱</Typography.Title><Typography.Paragraph type="secondary">全公司 AI 预算、额度与使用情况，一屏掌握。</Typography.Paragraph></div><Space><Tag color="blue">2026 年</Tag><Typography.Text type="secondary">数据更新时间：刚刚</Typography.Text></Space></div>{error && <Alert type="warning" showIcon message={error} description="请确认后端 API 已启动；页面仍保留结构化演示数据。" closable />}
    <Row gutter={[16,16]} className="metric-row"><Col xs={24} sm={12} xl={6}><Card loading={loading}><Statistic title="年度总预算" value={budget.totalAmount} precision={0} prefix="¥" valueStyle={{ color: '#10243d' }} /><span className="stat-foot"><ArrowUpOutlined /> 12.4% 较去年同期</span></Card></Col><Col xs={24} sm={12} xl={6}><Card loading={loading}><Statistic title="年度已使用" value={budget.usedAmount} precision={0} prefix="¥" /><Progress percent={budget.executionRate} size="small" strokeColor="#258bc5" format={v => `${v}% 执行率`} /></Card></Col><Col xs={24} sm={12} xl={6}><Card loading={loading}><Statistic title="部门共享额度" value={quota.allocatedAmount} precision={0} prefix="¥" /><Progress percent={quota.usageRate} size="small" strokeColor="#e6a23c" format={v => `${v}% 使用率`} /></Card></Col><Col xs={24} sm={12} xl={6}><Card><Statistic title="待处理预警" value={data?.unreadAlertCount ?? 0} prefix={<WarningOutlined />} valueStyle={{ color: '#e35757' }} /><span className="stat-foot warning">使用率达到阈值需要关注</span></Card></Col></Row>
    <Row gutter={[16,16]}><Col xs={24} xl={15}><Card title="费用趋势" extra={<Tag>按月</Tag>}><div className="trend-chart">{trend.map(item => <div className="trend-col" key={item.month}><div className="trend-bar" style={{ height: `${item.amount / 2.8}%` }} title={`${item.month} ¥${item.amount}k`} /><span>{item.month}</span></div>)}</div><div className="chart-caption"><span><i className="legend-dot blue" />实际费用（单位：千元）</span><span>年度累计 {money(budget.usedAmount)}</span></div></Card></Col><Col xs={24} xl={9}><Card title="使用率预警" extra={<BellOutlined />}><Space direction="vertical" size={14} style={{ width: '100%' }}><Alert type="error" showIcon message="产品研发部 · Codex" description="申请 ¥18,000 · 已用 ¥16,740" action={<b>93%</b>} /><Alert type="warning" showIcon message="市场部 · Claude Code" description="申请 ¥8,000 · 已用 ¥6,520" action={<b>81.5%</b>} /><Alert type="info" showIcon message="张小明 · UniAPI" description="申请 ¥1,000 · 已用 ¥800" action={<b>80%</b>} /></Space></Card></Col></Row>
    <Row gutter={[16,16]} className="lower-row"><Col xs={24} xl={12}><Card title="部门费用排行" extra={<FundOutlined />}><Table size="small" pagination={false} dataSource={deptRows} columns={[{ title: '部门', dataIndex: 'dept' }, { title: '费用', dataIndex: 'amount', render: money }, { title: '预算执行率', dataIndex: 'rate', render: (value: number) => <Progress percent={value} size="small" /> }]} /></Card></Col><Col xs={24} xl={12}><Card title="项目费用概览" extra={<DollarOutlined />}><Table size="small" pagination={false} dataSource={projectRows} columns={[{ title: '项目', dataIndex: 'project' }, { title: '所属部门', dataIndex: 'dept', render: (value: string) => <Tag>{value}</Tag> }, { title: '费用', dataIndex: 'amount', render: money }]} /></Card></Col></Row>
  </div>;
}
