import { Alert, Button, Card, DatePicker, Form, Input, InputNumber, Select, Space, Typography, message } from 'antd';
import { ArrowLeftOutlined } from '@ant-design/icons';
import { Controller, useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { createApplication, getProjects, getTools } from '../services/applications';
import type { Project, Tool } from '../types/api';
import { ApiError } from '../lib/http';

const schema = z.object({ type: z.enum(['quota', 'extra_usage', 'tool_access']), requestedAmount: z.number({ required_error: '请输入申请金额' }).positive('申请金额必须大于 0'), projectId: z.string().min(1, '请选择所属项目'), toolId: z.string().min(1, '请选择 AI 工具'), reason: z.string().trim().min(10, '申请原因至少填写 10 个字'), expectedUsage: z.string().trim().min(1, '请填写预计用量'), dateRange: z.tuple([z.any(), z.any()]).optional() });
type FormValues = z.infer<typeof schema>;
export function NewApplicationPage() { const navigate = useNavigate(); const [projects, setProjects] = useState<Project[]>([]); const [tools, setTools] = useState<Tool[]>([]); const [loadError, setLoadError] = useState(''); const [submitting, setSubmitting] = useState(false); const { control, handleSubmit, formState: { errors }, reset } = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: { type: 'quota', requestedAmount: undefined, projectId: '', toolId: '', reason: '', expectedUsage: '' } });
  useEffect(() => { Promise.all([getProjects(), getTools()]).then(([projectData, toolData]) => { setProjects(projectData); setTools(toolData); }).catch(e => setLoadError(e instanceof ApiError ? e.message : '基础数据加载失败')); }, []);
  const submit = async (values: FormValues) => { setSubmitting(true); try { const [start, end] = values.dateRange ?? []; const result = await createApplication({ type: values.type, requestedAmount: values.requestedAmount, projectId: values.projectId, toolId: values.toolId, reason: values.reason, expectedUsage: values.expectedUsage, startDate: start?.format?.('YYYY-MM-DD'), endDate: end?.format?.('YYYY-MM-DD') }); message.success(`申请 ${result.applicationNo} 已提交`); navigate('/applications'); } catch (e) { message.error(e instanceof Error ? e.message : '提交失败'); } finally { setSubmitting(false); } };
  return <div className="page-wrap narrow-page"><Button type="link" icon={<ArrowLeftOutlined />} onClick={() => navigate('/applications')}>返回申请列表</Button><Card className="form-card"><Typography.Title level={2}>新建申请</Typography.Title><Typography.Paragraph type="secondary">填写额度或额外使用申请，提交后由对应审批人处理。</Typography.Paragraph>{loadError && <Alert type="warning" showIcon message={loadError} />}{!loadError && <form onSubmit={handleSubmit(submit)}><Form.Item label="申请类型" validateStatus={errors.type ? 'error' : ''} help={errors.type?.message}><Controller name="type" control={control} render={({ field }) => <Select {...field} options={[{ value: 'quota', label: '额度申请' }, { value: 'extra_usage', label: '额外使用申请' }, { value: 'tool_access', label: '工具权限申请' }]} />} /></Form.Item><Form.Item label="申请金额" validateStatus={errors.requestedAmount ? 'error' : ''} help={errors.requestedAmount?.message}><Controller name="requestedAmount" control={control} render={({ field }) => <InputNumber {...field} value={field.value} onChange={field.onChange} min={0.01} precision={2} prefix="¥" style={{ width: '100%' }} placeholder="请输入金额" />} /></Form.Item><Form.Item label="所属项目" validateStatus={errors.projectId ? 'error' : ''} help={errors.projectId?.message}><Controller name="projectId" control={control} render={({ field }) => <Select {...field} placeholder="请选择项目" options={projects.map(project => ({ value: project.id, label: `${project.name}（${project.departmentName}）` }))} />} /></Form.Item><Form.Item label="AI 工具" validateStatus={errors.toolId ? 'error' : ''} help={errors.toolId?.message}><Controller name="toolId" control={control} render={({ field }) => <Select {...field} placeholder="请选择工具" options={tools.map(tool => ({ value: tool.id, label: `${tool.name} · ${tool.billingType}` }))} />} /></Form.Item><Form.Item label="预计使用周期"><Controller name="dateRange" control={control} render={({ field }) => <DatePicker.RangePicker value={field.value as any} onChange={field.onChange} />} /></Form.Item><Form.Item label="预计用量" validateStatus={errors.expectedUsage ? 'error' : ''} help={errors.expectedUsage?.message}><Controller name="expectedUsage" control={control} render={({ field }) => <Input {...field} placeholder="例如：预计使用 Token 500 万，周期 30 天" />} /></Form.Item><Form.Item label="申请原因" validateStatus={errors.reason ? 'error' : ''} help={errors.reason?.message}><Controller name="reason" control={control} render={({ field }) => <Input.TextArea {...field} rows={5} showCount maxLength={500} placeholder="请说明业务背景、使用场景和预期效果，至少 10 个字" />} /></Form.Item><Space><Button onClick={() => { reset(); navigate('/applications'); }}>取消</Button><Button type="primary" htmlType="submit" loading={submitting}>提交申请</Button></Space></form>}</Card></div>;
}


