import { Alert, Card, DatePicker, Form, Select, Table, Tag, Typography, message } from 'antd';
import { useEffect, useState } from 'react';
import { getUsages } from '../services/usage';
import type { UsageRecord } from '../types/api';
import { ApiError } from '../lib/http';
const money = (value: number) => `¥ ${value.toLocaleString('zh-CN', { maximumFractionDigits: 2 })}`;
export function UsagePage() {
  const [rows, setRows] = useState<UsageRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [pagination, setPagination] = useState({ current: 1, pageSize: 20, total: 0 }); const [filters, setFilters] = useState<{ projectId?: string }>({});
  const load = (page = pagination.current, pageSize = pagination.pageSize) => { setLoading(true); getUsages({ page, pageSize, ...filters }).then(result => { setRows(result.items); setPagination({ current: result.pagination.page, pageSize: result.pagination.pageSize, total: result.pagination.total }); setError(''); }).catch(e => { setError(e instanceof ApiError ? e.message : '费用数据加载失败'); message.error('费用数据加载失败'); }).finally(() => setLoading(false)); };
  useEffect(() => { load(1, pagination.pageSize); }, [filters]);
  const columns = [{ title: '使用时间', dataIndex: 'occurredAt', render: (value: string) => new Date(value).toLocaleString('zh-CN') }, { title: '员工', dataIndex: 'employeeName' }, { title: '部门', dataIndex: 'departmentName' }, { title: '工具', dataIndex: 'toolName', render: (value: string) => <Tag color="blue">{value}</Tag> }, { title: '项目', dataIndex: 'projectName', render: (value?: string) => value || <Typography.Text type="secondary">未归属</Typography.Text> }, { title: '用量', dataIndex: 'quantity', render: (value: number, row: UsageRecord) => `${value.toLocaleString()} ${row.usageType}` }, { title: '金额', dataIndex: 'amount', render: money }];
  return <div className="page-wrap"><div className="page-title"><div><Typography.Title level={2}>我的费用</Typography.Title><Typography.Paragraph type="secondary">查看 AI 工具、模型和项目的费用使用明细。</Typography.Paragraph></div></div>{error && <Alert type="error" showIcon message={error} description="请稍后重试或联系管理员。" action={<a onClick={() => load()}>重新加载</a>} closable />}<Card className="filter-card"><Form layout="inline" onValuesChange={(_, values) => setFilters({ projectId: values.projectId })}><Form.Item label="项目" name="projectId"><Select allowClear placeholder="全部项目" style={{ width: 190 }} options={[{ value: 'project_001', label: 'CRM 重构项目' }, { value: 'project_002', label: '数据平台项目' }, { value: 'project_003', label: '品牌内容中台' }]} /></Form.Item><Form.Item label="日期范围" name="date"><DatePicker.RangePicker /></Form.Item></Form></Card><Card title="费用记录" className="table-card"><Table rowKey="id" loading={loading} dataSource={rows} columns={columns} scroll={{ x: 900 }} pagination={{ current: pagination.current, pageSize: pagination.pageSize, total: pagination.total, showSizeChanger: true, showTotal: total => `共 ${total} 条`, onChange: (page, pageSize) => load(page, pageSize) }} /></Card></div>;
}
